version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Get versem binary
          command: |
            wget -O versem https://github.com/antham/versem/releases/download/v1.1.0/versem_linux_amd64 && \
            sudo mv versem /usr/bin && \
            chmod 777 /usr/bin/versem
      - run:
          name: Check version in pull request
          command: |
            if [[ -z "$CIRCLE_PR_NUMBER" ]]; then
                if [[ -z "$CI_PULL_REQUEST" ]]; then
                    URL="https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?head=$CIRCLE_PROJECT_USERNAME:$CIRCLE_BRANCH"
                    RESULT="`curl -X GET -u $GITHUB_ACCESS_TOKEN:x-oauth-basic $URL | jq ".[0].url"`"
                    [[ "$RESULT" == 'null' ]] && CI_PULL_REQUEST='' || CI_PULL_REQUEST="${RESULT//\"}"
                fi
                CIRCLE_PR_NUMBER="$(basename "$CI_PULL_REQUEST")"
            fi
            if [[ -n "$CIRCLE_PR_NUMBER" ]]; then
            versem label check $CIRCLE_PR_NUMBER
            fi
  create-release:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/antham/versem-circle
    steps:
      - checkout
      - run:
          name: Get versem binary
          command: |
            wget -O versem https://github.com/antham/versem/releases/download/v1.1.0/versem_linux_amd64 && \
            sudo mv versem /usr/bin && \
            chmod 777 /usr/bin/versem
      - run:
          name: Create release
          command: |
            versem release create $CIRCLE_SHA1
workflows:
  version: 2
  build:
    jobs:
      - build
  create-release:
    jobs:
      - create-release:
          filters:
            branches:
              only: master
